language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
